//-------------------------------------------------------------------
// Filename: hal_board.h
// Description: MCU-KIT1 board with CC2530
//-------------------------------------------------------------------
//-------------------------------------------------------------------
// CONSTANTS
//-------------------------------------------------------------------

// Board properties
#define BOARD_NAME                     "ZIGBEE-DMA2530"
#define NUM_LEDS                        4

// Clock
#define BSP_CONFIG_CLOCK_MHZ            32


//RFID_FLAG
#define HAL_BOARD_IO_FLAG_PORT        1 
#define HAL_BOARD_IO_FLAG_PIN         1

//CD2530_Test_Pin
#define HAL_BOARD_IO_TEST1_PORT     1
#define HAL_BOARD_IO_TEST1_PIN      3
#define HAL_BOARD_IO_TEST2_PORT     1
#define HAL_BOARD_IO_TEST2_PIN      4
#define HAL_BOARD_IO_TEST3_PORT     1
#define HAL_BOARD_IO_TEST3_PIN      5
#define HAL_BOARD_IO_TEST4_PORT     0
#define HAL_BOARD_IO_TEST4_PIN      0


// LEDs
#define HAL_BOARD_IO_LED_PORT          1 

//#define HAL_BOARD_IO_LED_1_PORT        1 
//#define HAL_BOARD_IO_LED_1_PIN         2
#define HAL_BOARD_IO_LED_1_PORT        1 
#define HAL_BOARD_IO_LED_1_PIN         0
#define HAL_BOARD_IO_LED_2_PORT        1 
#define HAL_BOARD_IO_LED_2_PIN         1
#define HAL_BOARD_IO_LED_3_PORT        1 
#define HAL_BOARD_IO_LED_3_PIN         3
#define HAL_BOARD_IO_LED_4_PORT        1 
#define HAL_BOARD_IO_LED_4_PIN         4

//DC
#define HAL_BOARD_IO_DC_1_PORT        2 
#define HAL_BOARD_IO_DC_1_PIN         0
#define HAL_BOARD_IO_DC_2_PORT        1 
#define HAL_BOARD_IO_DC_2_PIN         7

//TC72
#define HAL_BOARD_IO_TC72_SDI_PORT     0 
#define HAL_BOARD_IO_TC72_SDI_PIN      4
#define HAL_BOARD_IO_TC72_SCL_PORT     0 
#define HAL_BOARD_IO_TC72_SCL_PIN      5
#define HAL_BOARD_IO_TC72_SDO_PORT     0 
#define HAL_BOARD_IO_TC72_SDO_PIN      6
#define HAL_BOARD_IO_TC72_SSS_PORT     0 
#define HAL_BOARD_IO_TC72_SSS_PIN      7

//AT24C02(E2PROM)
#define HAL_BOARD_IO_E2PROM_SCL_PORT           0
#define HAL_BOARD_IO_E2PROM_SCL_PIN            6
#define HAL_BOARD_IO_E2PROM_SDA_PORT           0
#define HAL_BOARD_IO_E2PROM_SDA_PIN            7

//ITG
#define HAL_BOARD_IO_E2PROM_SCK_PORT           0
#define HAL_BOARD_IO_E2PROM_SCK_PIN            6
#define HAL_BOARD_IO_E2PROM_SDA_PORT           0
#define HAL_BOARD_IO_E2PROM_SDA_PIN            7


// SPI
#define HAL_BOARD_IO_SPI_MISO_PORT          0
#define HAL_BOARD_IO_SPI_MISO_PIN           6
#define HAL_BOARD_IO_SPI_MOSI_PORT          0
#define HAL_BOARD_IO_SPI_MOSI_PIN           4
#define HAL_BOARD_IO_SPI_CLK_PORT           0
#define HAL_BOARD_IO_SPI_CLK_PIN            5
#define HAL_BOARD_IO_SPI_CS_PORT            0
#define HAL_BOARD_IO_SPI_CS_PIN             7

//SHT
#define HAL_BOARD_IO_SHT_SCK_PORT           2
#define HAL_BOARD_IO_SHT_SCK_PIN            4
#define HAL_BOARD_IO_SHT_SDA_PORT           2
#define HAL_BOARD_IO_SHT_SDA_PIN            3

//SR04£¨³¬Éù²¨£©
#define HAL_BOARD_IO_SR04_TX_PORT           2
#define HAL_BOARD_IO_SR04_TX_PIN            3
#define HAL_BOARD_IO_SR04_RX_PORT           2
#define HAL_BOARD_IO_SR04_RX_PIN            4

//TCS (ÑÕÉ«)
#define HAL_BOARD_IO_TCS_S2_PORT           2
#define HAL_BOARD_IO_TCS_S2_PIN            3
#define HAL_BOARD_IO_TCS_S3_PORT           2
#define HAL_BOARD_IO_TCS_S3_PIN            4


// I2C 
#define HAL_BOARD_IO_I2C_SCL_PORT           0
#define HAL_BOARD_IO_I2C_SCL_PIN            5
#define HAL_BOARD_IO_I2C_SDA_PORT           0
#define HAL_BOARD_IO_I2C_SDA_PIN            4

// LED
#define HAL_BOARD_IO_LED_DATA_PORT          1

// A/D
#define HAL_BOARD_IO_ADC_PORT               0
#define HAL_BOARD_IO_ADC_CH                 0

// INT
#define HAL_BOARD_IO_INT_PORT               0
#define HAL_BOARD_IO_INT_PIN                1

// DO
#define HAL_BOARD_IO_DO_PORT                0
#define HAL_BOARD_IO_DO_PIN                 0

//OUT
#define HAL_BOARD_IO_OUT_PORT                1
#define HAL_BOARD_IO_OUT_PIN                 7

// UART
#define HAL_BOARD_IO_UART_TXD_PORT          0
#define HAL_BOARD_IO_UART_TXD_PIN           3
#define HAL_BOARD_IO_UART_RXD_PORT          0
#define HAL_BOARD_IO_UART_RXD_PIN           2

// UART1
#define HAL_BOARD_IO_UART1_TXD_PORT          1
#define HAL_BOARD_IO_UART1_TXD_PIN           6
#define HAL_BOARD_IO_UART1_RXD_PORT          1
#define HAL_BOARD_IO_UART1_RXD_PIN           7

// Debounce
#define HAL_DEBOUNCE(expr)    { char i; for (i=0; i<50; i++) { if (!(expr)) i = 0; } }

// Assert
#define HAL_ASSERT(szErrMsg) { halAssertHandler(szErrMsg); }

//-------------------------------------------------------------------
// MACROS
//-------------------------------------------------------------------

//CD2530_Test_Pin

#define HAL_BOARD_TEST1_DIR_IN()     MCU_IO_INPUT(HAL_BOARD_IO_TEST1_PORT, HAL_BOARD_IO_TEST1_PIN, MCU_IO_PULLUP)
#define HAL_BOARD_TEST2_DIR_IN()     MCU_IO_INPUT(HAL_BOARD_IO_TEST2_PORT, HAL_BOARD_IO_TEST2_PIN, MCU_IO_PULLUP)
#define HAL_BOARD_TEST3_DIR_IN()     MCU_IO_INPUT(HAL_BOARD_IO_TEST3_PORT, HAL_BOARD_IO_TEST3_PIN, MCU_IO_PULLUP)
#define HAL_BOARD_TEST4_DIR_IN()     MCU_IO_INPUT(HAL_BOARD_IO_TEST4_PORT, HAL_BOARD_IO_TEST4_PIN, MCU_IO_PULLUP)

#define HAL_BOARD_TEST1_VAL()        MCU_IO_GET(HAL_BOARD_IO_TEST1_PORT, HAL_BOARD_IO_TEST1_PIN)
#define HAL_BOARD_TEST2_VAL()        MCU_IO_GET(HAL_BOARD_IO_TEST2_PORT, HAL_BOARD_IO_TEST2_PIN)
#define HAL_BOARD_TEST3_VAL()        MCU_IO_GET(HAL_BOARD_IO_TEST3_PORT, HAL_BOARD_IO_TEST3_PIN)
#define HAL_BOARD_TEST4_VAL()        MCU_IO_GET(HAL_BOARD_IO_TEST4_PORT, HAL_BOARD_IO_TEST4_PIN)

//RFID_FLAG
#define HAL_FLAG_SET()                 MCU_IO_SET_HIGH(HAL_BOARD_IO_FLAG_PORT, HAL_BOARD_IO_FLAG_PIN)
#define HAL_FLAG_CLR()                 MCU_IO_SET_LOW(HAL_BOARD_IO_FLAG_PORT, HAL_BOARD_IO_FLAG_PIN)

// LED
#define HAL_LED_SET_1()                 MCU_IO_SET_HIGH(HAL_BOARD_IO_LED_1_PORT, HAL_BOARD_IO_LED_1_PIN)
#define HAL_LED_SET_2()                 MCU_IO_SET_HIGH(HAL_BOARD_IO_LED_2_PORT, HAL_BOARD_IO_LED_2_PIN)
#define HAL_LED_SET_3()                 MCU_IO_SET_HIGH(HAL_BOARD_IO_LED_3_PORT, HAL_BOARD_IO_LED_3_PIN)
#define HAL_LED_SET_4()                 MCU_IO_SET_HIGH(HAL_BOARD_IO_LED_4_PORT, HAL_BOARD_IO_LED_4_PIN)

#define HAL_LED_CLR_1()                 MCU_IO_SET_LOW(HAL_BOARD_IO_LED_1_PORT, HAL_BOARD_IO_LED_1_PIN)
#define HAL_LED_CLR_2()                 MCU_IO_SET_LOW(HAL_BOARD_IO_LED_2_PORT, HAL_BOARD_IO_LED_2_PIN)
#define HAL_LED_CLR_3()                 MCU_IO_SET_LOW(HAL_BOARD_IO_LED_3_PORT, HAL_BOARD_IO_LED_3_PIN)
#define HAL_LED_CLR_4()                 MCU_IO_SET_LOW(HAL_BOARD_IO_LED_4_PORT, HAL_BOARD_IO_LED_4_PIN)


#define HAL_LED_TGL_1()                 MCU_IO_TGL(HAL_BOARD_IO_LED_1_PORT, HAL_BOARD_IO_LED_1_PIN)
#define HAL_LED_TGL_2()                 MCU_IO_TGL(HAL_BOARD_IO_LED_2_PORT, HAL_BOARD_IO_LED_2_PIN)
#define HAL_LED_TGL_3()                 MCU_IO_TGL(HAL_BOARD_IO_LED_3_PORT, HAL_BOARD_IO_LED_3_PIN)
#define HAL_LED_TGL_4()                 MCU_IO_TGL(HAL_BOARD_IO_LED_4_PORT, HAL_BOARD_IO_LED_4_PIN)

//DC
#define HAL_DC_START_1()                MCU_IO_SET_HIGH(HAL_BOARD_IO_DC_1_PORT, HAL_BOARD_IO_DC_1_PIN)
#define HAL_DC_START_2()                MCU_IO_SET_HIGH(HAL_BOARD_IO_DC_2_PORT, HAL_BOARD_IO_DC_2_PIN)

#define HAL_DC_STOP_1()                 MCU_IO_SET_LOW(HAL_BOARD_IO_DC_1_PORT, HAL_BOARD_IO_DC_1_PIN)
#define HAL_DC_STOP_2()                 MCU_IO_SET_LOW(HAL_BOARD_IO_DC_2_PORT, HAL_BOARD_IO_DC_2_PIN)

//TC72
#define HAL_TC72_SDI_SET()              MCU_IO_SET_HIGH(HAL_BOARD_IO_TC72_SDI_PORT, HAL_BOARD_IO_TC72_SDI_PIN)
#define HAL_TC72_SCL_SET()              MCU_IO_SET_HIGH(HAL_BOARD_IO_TC72_SCL_PORT, HAL_BOARD_IO_TC72_SCL_PIN)
#define HAL_TC72_SSS_SET()              MCU_IO_SET_HIGH(HAL_BOARD_IO_TC72_SSS_PORT, HAL_BOARD_IO_TC72_SSS_PIN)

#define HAL_TC72_SDI_CLR()              MCU_IO_SET_LOW(HAL_BOARD_IO_TC72_SDI_PORT, HAL_BOARD_IO_TC72_SDI_PIN)
#define HAL_TC72_SCL_CLR()              MCU_IO_SET_LOW(HAL_BOARD_IO_TC72_SCL_PORT, HAL_BOARD_IO_TC72_SCL_PIN)
#define HAL_TC72_SSS_CLR()              MCU_IO_SET_LOW(HAL_BOARD_IO_TC72_SSS_PORT, HAL_BOARD_IO_TC72_SSS_PIN)

#define HAL_TC72_SDO_VAL() 	        MCU_IO_GET(HAL_BOARD_IO_TC72_SDO_PORT, HAL_BOARD_IO_TC72_SDO_PIN)

#define HAL_TC72_SDO_SET()              MCU_IO_SET_HIGH(HAL_BOARD_IO_TC72_SDO_PORT, HAL_BOARD_IO_TC72_SDO_PIN)

//AT24C02(E2PROM)
#define HAL_E2PROM_SCL_DIR_OUT()          MCU_IO_OUTPUT(HAL_BOARD_IO_E2PROM_SCL_PORT, HAL_BOARD_IO_E2PROM_SCL_PIN,0)
//#define HAL_E2PROM_SDA_DIR_OUT()          MCU_IO_OUTPUT(HAL_BOARD_IO_E2PROM_SDA_PORT, HAL_BOARD_IO_E2PROM_SDA_PIN,1)
//#define HAL_E2PROM_SDA_DIR_IN()           MCU_IO_INPUT(HAL_BOARD_IO_E2PROM_SDA_PORT, HAL_BOARD_IO_E2PROM_SDA_PIN,MCU_IO_PULLUP)

#define HAL_E2PROM_SCL_SET()              MCU_IO_SET_HIGH(HAL_BOARD_IO_E2PROM_SCL_PORT, HAL_BOARD_IO_E2PROM_SCL_PIN)
#define HAL_E2PROM_SCL_CLR()              MCU_IO_SET_LOW(HAL_BOARD_IO_E2PROM_SCL_PORT, HAL_BOARD_IO_E2PROM_SCL_PIN)

//#define HAL_E2PROM_SDA_SET()              MCU_IO_SET_HIGH(HAL_BOARD_IO_E2PROM_SDA_PORT, HAL_BOARD_IO_E2PROM_SDA_PIN)
//#define HAL_E2PROM_SDA_CLR()              MCU_IO_SET_LOW(HAL_BOARD_IO_E2PROM_SDA_PORT, HAL_BOARD_IO_E2PROM_SDA_PIN)

//#define HAL_E2PROM_SDA_VAL()              MCU_IO_GET(HAL_BOARD_IO_E2PROM_SDA_PORT, HAL_BOARD_IO_E2PROM_SDA_PIN)

//ITG
#define HAL_E2PROM_SCK_DIR_OUT()          MCU_IO_OUTPUT(HAL_BOARD_IO_E2PROM_SCK_PORT, HAL_BOARD_IO_E2PROM_SCK_PIN,1)
#define HAL_E2PROM_SDA_DIR_OUT()          MCU_IO_OUTPUT(HAL_BOARD_IO_E2PROM_SDA_PORT, HAL_BOARD_IO_E2PROM_SDA_PIN,1)
#define HAL_E2PROM_SDA_DIR_IN()           MCU_IO_INPUT(HAL_BOARD_IO_E2PROM_SDA_PORT, HAL_BOARD_IO_E2PROM_SDA_PIN,MCU_IO_PULLUP)

#define HAL_E2PROM_SCK_SET()              MCU_IO_OUTPUT(HAL_BOARD_IO_E2PROM_SCK_PORT, HAL_BOARD_IO_E2PROM_SCK_PIN,1)
#define HAL_E2PROM_SCK_CLR()              MCU_IO_OUTPUT(HAL_BOARD_IO_E2PROM_SCK_PORT, HAL_BOARD_IO_E2PROM_SCK_PIN,0)

#define HAL_E2PROM_SDA_SET()             MCU_IO_OUTPUT(HAL_BOARD_IO_E2PROM_SDA_PORT, HAL_BOARD_IO_E2PROM_SDA_PIN,1)
#define HAL_E2PROM_SDA_CLR()              MCU_IO_OUTPUT(HAL_BOARD_IO_E2PROM_SDA_PORT, HAL_BOARD_IO_E2PROM_SDA_PIN,0)

#define HAL_E2PROM_SDA_VAL()              MCU_IO_GET(HAL_BOARD_IO_E2PROM_SDA_PORT, HAL_BOARD_IO_E2PROM_SDA_PIN)

// LED_ALL
#define HAL_LED_PORT(val)              MCU_PORT_OUTPUT(HAL_BOARD_IO_LED_DATA_PORT, val)

// SPI
#define HAL_SPI_INIT()                 {MCU_IO_OUTPUT(HAL_BOARD_IO_SPI_MOSI_PORT, HAL_BOARD_IO_SPI_MOSI_PIN, 1);MCU_IO_OUTPUT(HAL_BOARD_IO_SPI_CLK_PORT, HAL_BOARD_IO_SPI_CLK_PIN, 1);MCU_IO_OUTPUT(HAL_BOARD_IO_SPI_CS_PORT, HAL_BOARD_IO_SPI_CS_PIN, 1);MCU_IO_INPUT(HAL_BOARD_IO_SPI_MISO_PORT, HAL_BOARD_IO_SPI_MISO_PIN,MCU_IO_PULLUP);}

#define HAL_SPI_MOSI_SET()             MCU_IO_SET_HIGH(HAL_BOARD_IO_SPI_MOSI_PORT, HAL_BOARD_IO_SPI_MOSI_PIN)
#define HAL_SPI_MOSI_CLR()             MCU_IO_SET_LOW(HAL_BOARD_IO_SPI_MOSI_PORT, HAL_BOARD_IO_SPI_MOSI_PIN)

#define HAL_SPI_CLK_SET()              MCU_IO_SET_HIGH(HAL_BOARD_IO_SPI_CLK_PORT, HAL_BOARD_IO_SPI_CLK_PIN)
#define HAL_SPI_CLK_CLR()              MCU_IO_SET_LOW(HAL_BOARD_IO_SPI_CLK_PORT, HAL_BOARD_IO_SPI_CLK_PIN)

#define HAL_SPI_CS_EN()                MCU_IO_SET_LOW(HAL_BOARD_IO_SPI_CS_PORT, HAL_BOARD_IO_SPI_CS_PIN)
#define HAL_SPI_CS_DIS()               MCU_IO_SET_HIGH(HAL_BOARD_IO_SPI_CS_PORT, HAL_BOARD_IO_SPI_CS_PIN)

#define HAL_SPI_MISO_VAL() 	       MCU_IO_GET(HAL_BOARD_IO_SPI_MISO_PORT, HAL_BOARD_IO_SPI_MISO_PIN)

//SHT
#define HAL_SHT_SCK_DIR_OUT()          MCU_IO_OUTPUT(HAL_BOARD_IO_SHT_SCK_PORT, HAL_BOARD_IO_SHT_SCK_PIN,0)
#define HAL_SHT_SCK_SET()              MCU_IO_OUTPUT(HAL_BOARD_IO_SHT_SCK_PORT, HAL_BOARD_IO_SHT_SCK_PIN,1)//MCU_IO_SET_HIGH(HAL_BOARD_IO_SHT_SCK_PORT, HAL_BOARD_IO_SHT_SCK_PIN)
#define HAL_SHT_SCK_CLR()              MCU_IO_OUTPUT(HAL_BOARD_IO_SHT_SCK_PORT, HAL_BOARD_IO_SHT_SCK_PIN,0)//MCU_IO_SET_LOW(HAL_BOARD_IO_SHT_SCK_PORT, HAL_BOARD_IO_SHT_SCK_PIN)

#define HAL_SHT_SDA_SET()              MCU_IO_OUTPUT(HAL_BOARD_IO_SHT_SDA_PORT, HAL_BOARD_IO_SHT_SDA_PIN,1)//MCU_IO_SET_HIGH(HAL_BOARD_IO_SHT_SDA_PORT, HAL_BOARD_IO_SHT_SDA_PIN)
#define HAL_SHT_SDA_CLR()              MCU_IO_OUTPUT(HAL_BOARD_IO_SHT_SDA_PORT, HAL_BOARD_IO_SHT_SDA_PIN,0)//MCU_IO_SET_LOW(HAL_BOARD_IO_SHT_SDA_PORT, HAL_BOARD_IO_SHT_SDA_PIN)
#define HAL_SHT_SDA_DIR_OUT()          MCU_IO_OUTPUT(HAL_BOARD_IO_SHT_SDA_PORT, HAL_BOARD_IO_SHT_SDA_PIN,1)
#define HAL_SHT_SDA_DIR_IN()           MCU_IO_INPUT(HAL_BOARD_IO_SHT_SDA_PORT, HAL_BOARD_IO_SHT_SDA_PIN,MCU_IO_PULLUP)
#define HAL_SHT_SDA_VAL()              MCU_IO_GET(HAL_BOARD_IO_SHT_SDA_PORT, HAL_BOARD_IO_SHT_SDA_PIN)

//SR04£¨³¬Éù²¨£©

#define HAL_SHT_TX_DIR_OUT()          MCU_IO_OUTPUT(HAL_BOARD_IO_SR04_TX_PORT, HAL_BOARD_IO_SR04_TX_PIN,0)
#define HAL_SHT_TX_SET()              MCU_IO_OUTPUT(HAL_BOARD_IO_SR04_TX_PORT, HAL_BOARD_IO_SR04_TX_PIN,1)
#define HAL_SHT_TX_CLR()              MCU_IO_OUTPUT(HAL_BOARD_IO_SR04_TX_PORT, HAL_BOARD_IO_SR04_TX_PIN,0)

#define HAL_SHT_RX_DIR_IN()           MCU_IO_INPUT(HAL_BOARD_IO_SR04_RX_PORT, HAL_BOARD_IO_SR04_RX_PIN,MCU_IO_PULLUP)
#define HAL_SHT_RX_VAL()              MCU_IO_GET(HAL_BOARD_IO_SR04_RX_PORT, HAL_BOARD_IO_SR04_RX_PIN)

//flame(»ðÑæ)
#define HAL_SHT_FLAME_DIR_IN()           MCU_IO_INPUT(HAL_BOARD_IO_ADC_PORT, HAL_BOARD_IO_ADC_CH,MCU_IO_PULLUP)
#define HAL_SHT_FLAME_VAL()              MCU_IO_GET(HAL_BOARD_IO_ADC_PORT, HAL_BOARD_IO_ADC_CH)

//TCS(ÑÕÉ«)
#define HAL_SHT_S2_DIR_OUT()          MCU_IO_OUTPUT(HAL_BOARD_IO_TCS_S2_PORT, HAL_BOARD_IO_TCS_S2_PIN,0)
#define HAL_SHT_S2_SET()              MCU_IO_OUTPUT(HAL_BOARD_IO_TCS_S2_PORT, HAL_BOARD_IO_TCS_S2_PIN,1)
#define HAL_SHT_S2_CLR()              MCU_IO_OUTPUT(HAL_BOARD_IO_TCS_S2_PORT, HAL_BOARD_IO_TCS_S2_PIN,0)

#define HAL_SHT_S3_DIR_OUT()          MCU_IO_OUTPUT(HAL_BOARD_IO_TCS_S3_PORT, HAL_BOARD_IO_TCS_S3_PIN,0)
#define HAL_SHT_S3_SET()              MCU_IO_OUTPUT(HAL_BOARD_IO_TCS_S3_PORT, HAL_BOARD_IO_TCS_S3_PIN,1)
#define HAL_SHT_S3_CLR()              MCU_IO_OUTPUT(HAL_BOARD_IO_TCS_S3_PORT, HAL_BOARD_IO_TCS_S3_PIN,0)

// I2C
#define HAL_I2C_SCL_DIR_OUT()          MCU_IO_OUTPUT(HAL_BOARD_IO_I2C_SCL_PORT, HAL_BOARD_IO_I2C_SCL_PIN,0)
#define HAL_I2C_SCL_SET()              MCU_IO_SET_HIGH(HAL_BOARD_IO_I2C_SCL_PORT, HAL_BOARD_IO_I2C_SCL_PIN)
#define HAL_I2C_SCL_CLR()              MCU_IO_SET_LOW(HAL_BOARD_IO_I2C_SCL_PORT, HAL_BOARD_IO_I2C_SCL_PIN)

#define HAL_I2C_SDA_SET()              MCU_IO_SET_HIGH(HAL_BOARD_IO_I2C_SDA_PORT, HAL_BOARD_IO_I2C_SDA_PIN)
#define HAL_I2C_SDA_CLR()              MCU_IO_SET_LOW(HAL_BOARD_IO_I2C_SDA_PORT, HAL_BOARD_IO_I2C_SDA_PIN)
#define HAL_I2C_SDA_DIR_OUT()          MCU_IO_OUTPUT(HAL_BOARD_IO_I2C_SDA_PORT, HAL_BOARD_IO_I2C_SDA_PIN,1)
#define HAL_I2C_SDA_DIR_IN()           MCU_IO_INPUT(HAL_BOARD_IO_I2C_SDA_PORT, HAL_BOARD_IO_I2C_SDA_PIN,MCU_IO_PULLUP)
#define HAL_I2C_SDA_VAL()              MCU_IO_GET(HAL_BOARD_IO_I2C_SDA_PORT, HAL_BOARD_IO_I2C_SDA_PIN)

// DO
#define HAL_DO_OFF()                   MCU_IO_SET_HIGH(HAL_BOARD_IO_DO_PORT, HAL_BOARD_IO_DO_PIN)
#define HAL_DO_ON()                    MCU_IO_SET_LOW(HAL_BOARD_IO_DO_PORT, HAL_BOARD_IO_DO_PIN)
#define HAL_DO_OUTPUT()                MCU_IO_OUTPUT(HAL_BOARD_IO_DO_PORT, HAL_BOARD_IO_DO_PIN, 1)

//INT
#define HAL_INT_VAL() 	               MCU_IO_GET(HAL_BOARD_IO_INT_PORT, HAL_BOARD_IO_INT_PIN)

//OUT
#define HAL_OUT_VAL() 	               MCU_IO_GET(HAL_BOARD_IO_OUT_PORT, HAL_BOARD_IO_OUT_PIN)


//-------------------------------------------------------------------
// FUNCTION PROTOTYPES
//-------------------------------------------------------------------
void halBoardInit(void);

